version: "3.8"

services:
  springboot-app:
    image: ajithak7353/springboot-ci-cd:latest

    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot_app
    ports:
      - "9090:9090"
    restart: always
